= Korolev: Single Page Applications Framework

Aleksey Fomkin <aleksey.fomkin@gmail.com>
:source-highlighter: pygments
:numbered:
:toc:

== Introduction

Not long ago we have entered the era of single-page applications. Some people say that we no longer need a server. They say that JavaScript applications can connect to DBMS directly. Fat clients. We disagree with this. This project is an attempt to solve the problems of the modern fat web.

Korolev runs a single-page application on the server side, keeping in the browser only a bridge to receive commands and send events. The page loads instantly and works fast because it does a minimal amount of computation. It's important that Korolev provides a unified environment for full stack development. Client and server are now combined into a single app without any REST protocol or something else in the middle.

Our project supports static page rendering so that search engines could index pages and users could view them immediately.

=== Principles

1. **Thin client.** Let's be honest, modern JavaScript applications are too greedy. Every JavaScript developer thinks that his page is special. But the user has a different opinion. He opens dozens of tabs. Each tab contains a ton of code, and this works very slowly. So we made our JavaScript bridge as lightweight as possible.

2. **Immutable and pure.** Really, we don't need mutability even on the frontend. Especially on the frontend. The majority of modern JavaScript frameworks try to be functional. So we do.

3. **Lack of dependencies.** Korolev does not impose to use cats, scalaz, Akka, or futures from the standard library. Use what you want. Korolev gives a way to integrate itself into any environment.

=== Quick start

You need SBT 0.13.15 and JDK 8+ installed. Once installed, run g8 template.

[source,bash]
-----------------------------------
$ sbt new fomkin/korolev.g8
$ cd mykorolevproject
$ sbt
> re-start
-----------------------------------

Ok, now you are ready to start hacking with Korolev.

== Understanding Korolev

=== Template DSL

Korolev uses https://github.com/fomkin/levsha[Levsha] as DSL (domain specific language) for templating. The levsha DSL allows to declare DOM using Scala code. Take a look.

[source,scala]
-----------------------------------
'div(
  'backgroundColor @= "yellow",
  'input('type /= "text")
)
-----------------------------------

This code fragment corresponds to HTML below.

[source,html]
-----------------------------------
<div style="background-color: yellow">
  <input type="text"></input>
</div>
-----------------------------------

As you can see there are three simple rules:

1. `'tag()` declares tag
2. `'attribute /= "value"` declares attribute
3. `'backgroundColor @= "black"` declares style

And one more special thing. Use `:=` when you want to set attribute as an element's property. It may be useful when some data can be passed through attribute. For example value of `'input`.

[NOTE]
==========================
Style keys are camelCased in order to be consistent with accessing the properties on DOM nodes from JS (e.g. node.style.backgroundImage). Vendor prefixes other than ms should begin with a capital letter. This is why WebkitTransition has an uppercase "W".
==========================

=== Device and Session

When a user opens Korolev application the first time, it sets a cookie named `device` with a unique identifier. After that, you can identify the user by `deviceId`.

A session is created when the user opens a page. Every session has a unique identifier `sessionId`. Korolev has a separate _State_ for every session.

=== State

State is the only source of data needed to render a page. If you have something you want to display, it should be stored in state. State is always immutable.

[source,scala]
-----------------------------------
sealed trait MyState

case class Anonymous(
  deviceId: DeviceId) extends MyState

case class Authorized(
  deviceId: DeviceId,
  user: User) extends MyState

case class User(
  id: String,
  name: String,
  friends: Seq[String])
-----------------------------------

State is stored in `StateStorage`.

[source,scala]
-----------------------------------
StateStorage[Future, MyState].forDeviceId { deviceId =>
  // This hypothetical service method returns Future[User]
  authorizationService.getUserByDeviceId(deviceId) map { user =>
    Authorized(deviceId, user)
  }
}
-----------------------------------

The only way to modify the State is by applying a *transition* (see below).

=== Render

Render is a view of the state. Render is a function which takes state as an argument and returns a DOM. Korolev has its own DSL to define templates using Scala code. Do not be afraid, you will quickly get used to it.

[source,scala]
-----------------------------------
val render: Render = {
  case Anonymous(_) =>
    'body(
      'form(
        'input('placeholder /= "Login"),
        'input('placeholder /= "Password"),
        'button("Submit")
      )
    )
  case Authorized(_, User(name, friends)) =>
    'body(
      'div(s"Your name is $name. Your friends:"),
      'ul(
        // Look at that. You just map data to view
        friends map { friend =>
          'li(friend)
        }
      )
    )
}
-----------------------------------

Render is called for each new state. It's important to understand that render produces a full DOM for every call. It does not mean that client receives a new page every time. Korolev makes a diff between current and latest DOM. Only changes between the two are sent to the client.

`Render` is a type alias for `PartialFunction[S, Document.Node]` where `S` is a type of your state.

[NOTE]
==========================
Currently, top-level render method must wrap its content into `body` element. This limitation will be removed in a future version.
==========================

=== Transitions

Transition is a function that applies to the current state and produces a new state. Consider a transition which adds a new friend to the friends list.

[source,scala]
--------------------------------------------------------------
val newFriend = "Karl Heinrich Marx"
// This hypothetical service method adds friend
// to the user friend list and returns Future[Unit]
userService.addFriend(user.id, newFriend) flatMap { _ =>
  access.transition { case state @ Authorized(_, user) =>
    state.copy(user = user.copy(user.friends :+ newFriend))
  }
}
--------------------------------------------------------------

`Transition` is a type alias for `S => S` where `S` is the type of your state.

=== Events

Every DOM event emitted which had been emitted by browser's `document` object, can be handled by Korolev. Let's consider click event.

[source,scala]
--------------------------------------------------------------
case class MyState(i: String)

val renderAnonymous: Render = {
  case MyState(i) =>
    'body(
      i.toString,
      'button("Increment",
        event('click) { access =>
          access.transition {
            case MyState(i) =>
              state.copy(i = i + 1)
          }
        }
      )
    )
}
--------------------------------------------------------------

When "Increment" button will be clicked, `i` will be incremented by 1. Let's consider a more complex situation. Do you remember render example? Did you have a feeling that something was missing? Let's complement it with events!

[source,scala]
-----------------------------------
val loginField = elementId()
val passwordField = elementId()

val renderAnonymous: Render = {
  case Anonymous(_) =>
    'body(
      'form(
        'input('placeholder /= "Login", loginField),
        'input('placeholder /= "Password", passwordField),
        'button("Submit"),
        event('submit) { access =>
          for {
            login <- access.property(loginField, 'value)
            password <- access.property(passwordField, 'value)
            user <- authService.authorize(login, password)
            _ <- access.transition {
              case Anonymous(deviceId) =>
                Authorized(deviceId, user)
            }
          } yield ()
        }
      )
    )
}

val renderAuthorized: Render = ???
val render = renderAnonymous orElse renderAuthorized
-----------------------------------

Event gives you an access to information from the client side. In this case, it it is values of the input fields. Also you can get data from event object using `access.eventData` function`.

Event handlers should return F[Unit] which will be implicitly converted to `EventResult`.

=== Stateful components

In the world of front-end development people often call every thing that has HTML-like markup a "component". Until version 0.6, Korolev didn't have components support (except WebComponents on client side). When we say "component" we mean something that has its own state. In Korolev case, components also dispatch events to other components up in the hierarchy or to the application on the top.

Worth to note that application is a component too, so you can consider Korolev's components system as a system composed of applications. Korolev components are not lightweight, so if you can implement a feature without components, do it so. Use components only when they are really necessary.

Components are independent. Every component has its own context. It opens up a way to write reusable code.

There are two ways to define a component: in functional and in object-oriented style. Let's take a look at functional style components.

[source,scala]
-----------------------------------
val MyComponent = Component[Future, ComponentState, ComponentParameters, EventType](initialState) { (context, parameters, state) =>

  import context._
  import symbolDsl._

  'div(
    parameters.toString,
    state.toString,
    event('click) { access =>
      // Change component state here
      // using transition as usual.
    }
  )
}
-----------------------------------

Same component can be defined in object-oriented style.

[source,scala]
-----------------------------------
object MyComponent extends Component[Future, ComponentState, ComponentParameters, EventType](initialState) {

  import context._
  import symbolDsl._

  def render(parameters: ComponentParameters, state: ComponentState): Node = {
    'div(
      parameters.toString,
      state.toString,
      event('click) {
        // Change component state here
      }
    )
  }
}
-----------------------------------

Let's use our component in the application.

[source,scala]
-----------------------------------
'body(
  "Hello world!",
  MyComponent(parameters) { (access, _) =>
    // make transition on component event
    access.transition {
      case n => n + 1
    }
  },
  // If you don't want to handle event, use silent instance
  MyComponent.silent(parameters)
)
-----------------------------------

https://github.com/fomkin/korolev/blob/v0.8.0/examples/component/src/main/scala/ComponentExample.scala[See full example]

=== Access element properties

In the scope of an event, you can access the element properties if an element was bound with `elementId`. You get the value as a string. If the value is an object (on client side) you will get JSON-string. You can parse it with any JSON-library you want.

[source,scala]
-----------------------------------
val loginField = elementId()

...

event('submit) { access =>
  access.property(loginField, 'value) flatMap {
    access.transition { ... }
  }
}
-----------------------------------

Or you can set the value

[source,scala]
-----------------------------------
access.property(loginField).set('value, "John Doe")
-----------------------------------

Also you can use shortcut `valueOf` for get values from elements.

=== FormData

Above, we considered a method allowing to read values and update form inputs. The flaw of this is the need of reading input one-by-one and lack of files uploading. FormData attended to solve these problems.

In contrast to `property`, FormData works with form tag, not with input tag.

[source,scala]
-----------------------------------
val myForm = elementId()
val pictureFieldName = "picture"

'form(
  myForm,
  'div(
    'legend("FormData Example"),
    'p(
      'label("Picture"),
      'input('type /= "file", 'name /= pictureFieldName)
    ),
    'p(
      'button("Submit")
    )
  ),
  event('submit) { access =>
    access
      .downloadFormData(myForm)
      .onProgress { (loaded, total) => state =>
        state.copy(loaded = loaded, total = total)
      }
      .start()
      .flatMap { formData =>
        access.transition { ... }
      }
  }
)
-----------------------------------

Use `onProgress` callback to handle progress of the form downloading. Function `start` return a `FormData`. Look API documentation for more details.

https://github.com/fomkin/korolev/blob/v0.8.0/examples/form-data/src/main/scala/FormDataExample.scala[See full example]

=== Delays

Sometimes you want to update a page after a timeout. For example it is useful when you want to show some sort of notification and have to close it after a few seconds. Delays apply transition after a given `FiniteDuration`

[source,scala]
-----------------------------------
type MyState = Boolean

val render: Render = {
  case true => 'body(
    delay(3.seconds) { access =>
      access.transition(_ => false)
    },
    "Wait 3 seconds!"
  )
  case false => 'body(
    'button(
      event('click) { access =>
        access.transition(_ => true)
      },
      "Push the button"
    )
  )
}
-----------------------------------

https://github.com/fomkin/korolev/blob/v0.8.0/examples/delay/src/main/scala/DelayExample.scala[See full example]

=== Environment configurator

Korolev is not just request-response, but also push. One of the big advantages of Korolev is the ability to display server side events without additional code. Consider example where we have a page with some sort of notifications list.

[source,scala]
-----------------------------------
case class MyState(notifications: List[String])

var render: Render = {
  case MyState(notifications) =>
    'ul(
      notifications.map(notification =>
        'li(notification)
      )
    )
}
-----------------------------------

Also, we have a message queue which has a topic with notifications for current user. The topic has identifier based on `deviceId` of a client. Lets try to bind an application state with messages from the queue.

[source,scala]
-------------------------------------------------------------------------------
KorolevServiceConfig(
  ...
  envConfigurator = EnvConfigurator { (deviceId, sessionId, applyTransition) =>
    messageQueue.subscribe(deviceId, sessionId).map { subscription =>
      applyTransition {
        case state: MyState =>
          state.copy(notifications = notification :: state.notifications)
      }

      KorolevServiceConfig.Env(
        onDestroy = () => subscription.unsubscribe(),
        onMessage = {
          case message => subscription.send(message)
        }
      )
    }
)
-------------------------------------------------------------------------------

Now you can use `Access.publish(message)` to send messages to the queue and every invocation of lambda which was passed to `messageQueue.subscribe` will run the transition which will prepend notifications to the state. Render will be invoked automatically and user will get his page updated.

=== Routing

Router allows to integrate browser navigation into you app. In the router you define bidirectional mapping between the state and the URL.

Let's pretends that your application is a blogging platform.

[source,scala]
-------------------------------------------------------------------------------
case class MyState(author: String, title: String, text: String)

// Converts "The Cow: Saga" to "the-cow-saga"
def captionToUrl(s: String) = ???

KorolevServiceConfig(
  ...
  // Render the article
  render = {
    case MyState(author, title, text) => 'body(
      'div(s"$author: $title"),
      'div(text)
    )
  },
  router = Router(
    // Static router works when user enters
    // with any url but "/".
    static = (deviceId) => Router(
      toState = {
        case (_, Root / author / article) => articleService.load(author, article)
        case _ => articleService.defaultArticle
      }
    ),
    dynamic = (device, session) => Router(
      fromState = {
        case MyState(tab, _) =>
          Root / tab.toLowerCase
      },
      toState = {
        case (s, Root) =>
          val u = s.copy(selectedTab = s.todos.keys.head)
          Future.successful(u)
        case (s, Root / name) =>
          val key = s.todos.keys.find(_.toLowerCase == name)
          Future.successful(key.fold(s)(k => s.copy(selectedTab = k)))
      }
    )
  )
)
-------------------------------------------------------------------------------

https://github.com/fomkin/korolev/blob/v0.8.0/examples/routing/src/main/scala/RoutingExample.scala#L93[See full example]

==== Running at a nested path

If Korolev is running at a nested path, e.g. `/ui/`, router's `rootPath` parameter should be set to a desired value:

[source,scala]
-------------------------------------------------------------------------------
router = Router(
  static = ...,
  dynamic = ...,
  rootPath = "/ui/"
)
-------------------------------------------------------------------------------

== Productivity

=== Web Components

Usually when we say "components" we mean a UI element with its own state. Korolev doesn't support components by design, cause it leads to multiple states and breaks the simplicity which we want to reach. However you still can use https://www.w3.org/standards/techs/components[WebComponents].

[NOTE]
============
Korolev doesn't have any specific code to support WebComponents. WebComponent (Custom Elements + Shadow DOM) by design should behave as regular HTML tags. There is no difference between, for example, input or textarea, and any custom element.
============

https://github.com/fomkin/korolev/blob/v0.8.0/examples/web-component/src/main/scala/WebComponentExample.scala[See full example]

=== Developer mode and "hot reload"

Developer mode provides "hot reload" experience. Run your application with `korolev.dev=true` system property (or environment variable) and session will be kept alive after restart. We recommend to use https://github.com/spray/sbt-revolver[sbt-revolver] plugin.

[source,bash]
-------------------------------------------------------------------------------
re-start --- -Dkorolev.dev=true
-------------------------------------------------------------------------------

Make a change to your app source code and save the file. Switch to the browser and wait for changes to deliver.

Notice that developer mode does not work with custom `StateStorage`.

[NOTE]
============
Ensure that everything is stateless except Korolev part of the application. For example, if you keep some state outside of Korolev state, it won't be saved and will lead to inconsistency.
============

=== Serve files from resource directory

Everything placed in directory named `static` (in the classpath of the application) will be served from the root of the application endpoint. It may be useful when you want to distribute some small images or CSS with the app.

[WARNING]
============
Korolev is not some sort of CDN node. Avoid serving lots of large files using this feature.
============

== Integrations

=== JCache

For large applications, when one node can't serve all clients, you need a way to scale application to multiple nodes. Although Korolev usually use persistent connections, a case when a client connects to a wrong node is possible. First, it may happen after reconnect. Secondly, it may happen when the client downgrades his connection from WebSocket to long polling for some reason. It means that every node in a cluster should have access to all user states (sessions).

To fix this, you can apply any in-memory storage compatible with https://github.com/jsr107/jsr107spec[JCache]. Just add a dependency to your SBT configuration.

[source,scala]
------------------------------
libraryDependencies += "com.github.fomkin" %% "korolev-jcache-support" % "0.6.1"
------------------------------

https://github.com/fomkin/korolev/blob/v0.8.0/examples/jcache/src/main/scala/JCacheExample.scala[See full example]

=== Akka HTTP

Korolev provides smooth Akka HTTP integration out of the box. To use it, add a dependency:

[source,scala]
------------------------------
libraryDependencies += "com.github.fomkin" %% "korolev-server-akkahttp" % "0.6.1"
------------------------------

And create Korolev route:

[source,scala]
------------------------------
val config = KorolevServiceConfig[Future, Boolean, Any](
  stateStorage = StateStorage.default(false),
  router = Router.empty[Future, Boolean],
  render = { case _ => 'body('div("Hello akka-http")) }
)

val korolevRoute = akkaHttpService(config).apply(AkkaHttpServerConfig())
------------------------------

Then embed the route into your Akka HTTP routes structure.

https://github.com/fomkin/korolev/blob/v0.8.0/examples/akka-http/src/main/scala/AkkaHttpExample.scala[See full example]

=== Monix

Monix integration module provides `Async` implementation using `monix.eval.Task`. To use it, add a dependency:

[source,scala]
------------------------------
libraryDependencies += "com.github.fomkin" %% "korolev-monix-support" % "0.6.1"
------------------------------

[source,scala]
------------------------------
import korolev.execution._
import korolev.monixSupport._
import monix.eval.Task

val config = KorolevServiceConfig[Task, Boolean, Any](
  stateStorage = StateStorage.default(false),
  router = Router.empty[Task, Boolean],
  render = { case _ => 'body('div("Hello Monix Task")) }
)
------------------------------

https://github.com/fomkin/korolev/blob/v0.8.0/examples/monix/src/main/scala/MonixExample.scala[See full example]
